### ISSUE TITLE
setup.py does not specify entry_points

### ISSUE THREAD

**Issue by charlesdaniels** [jyn514/GradeForge#38]
Since we are already using `setup.py`, we should use entry points for all installed scripts. Entry points allow one or more "main" functions to be connected to commands in `$PATH` autoamtically by `setup.py install`. Here is an example from a recent project of mine:

```python
    entry_points = {
        'console_scripts': ['quadp-cli=quadp.cli:main']
    }
```
[Here](https://stackoverflow.com/questions/774824/explain-python-entry-points) is a stackoverflow post with more details. 

I am capable of implementing this myself as soon as @jyn514 can enumerate a list of desired entry points.

**Comment by jyn514** [comment]
Hmm, there's not really a single function which handles this. is there a way to specify all of `__main__.py` as an entry point?

**Comment by jyn514** [comment]
I think [`pkg_resources.EntryPoint`](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#creating-and-parsing) might do what we want, testing now

**Comment by jyn514** [comment]
Done in https://github.com/jyn514/GradeForge/commit/ef7e556aeef41fb238ad56bd5ca3ce14f083c17d, it ended up being easier than I thought
