### ISSUE TITLE
make dependencies part of makefile

### ISSUE THREAD

**Issue by jyn514** [jyn514/GradeForge#40]
This would lower the burden on the end user and also simplify travis builds slightly. The only difficult thing would be to install in both a system environment (`/usr/bin/pip`) and virtualenv. `pip install --user` [does not work in a virtual environment](https://github.com/pypa/pip/issues/4141).

I'm open to suggestions :)

**Comment by charlesdaniels** [comment]
A virtualenv[1] would be the way to do this... I for one would be annoyed if I downloaded a repo and `make` started making changes to my environment without asking (as opposed to `make install` or something). 

1 - https://iamzed.com/2009/05/07/a-primer-on-virtualenv/

**Comment by jyn514** [comment]
Hmm, fair. I'll look into it.

**Comment by jyn514** [comment]
how would you expect it to behave if you were already in a virtualenv? Is it possible to nest them?

**Comment by charlesdaniels** [comment]
I don't think so... if I was already in a virtualenv I would want it to just do it’s thing into that virtualenv.

**Comment by jyn514** [comment]
There doesn't appear to be a way to source a virtual environment for all recipies in a makefile, we'd have to do it for each individually. The closest we could get is a wrapper for make, similar to `./gradlew`. I really don't want to do that, though.

**Comment by jyn514** [comment]
Pushing my current code so you have it available, but I'm a little dubious about this. It might be better to remove dependencies from the makefile altogether.

**Comment by charlesdaniels** [comment]
That’s what I would suggest. I am under the impression that it is a pretty standard python development workflow to setup your virtualenv and install your dependencies via setup.py. If the user finds 

source /some/virtualenv/bin/activate 
python setup.py install 

Too onerous, they can script it themselves.

**Comment by jyn514** [comment]
[got it](https://github.com/jyn514/GradeForge/commit/8bba2448c22556573c1041924f4f418decdc5b33), you can pass ENV and BASH_ENV to sh and bash respectively and they'll source that on startup

**Comment by jyn514** [comment]
err . . . so we don't think this was a helpful thing to do? I don't really care either way since I only have to install once, I just feel a little silly that I spent time on it

**Comment by jyn514** [comment]
done in https://github.com/jyn514/GradeForge/commit/0451585a9a6016cb9e257c27da6b88fceb0786b4
